### ISSUE TITLE
Not all digraphs are supported

### ISSUE THREAD

**Issue by Rizhiy** [protex/better-digraphs.nvim#11]
Hi, I tried to insert λ (digraph `*l`), but was not able to find it.

Where do you take digraph map from?

**Comment by Rizhiy** [comment]
NVM, I'm an idiot, it is `l*`

**Comment by protex** [comment]
For future reference, I pulled the diagraph list from vim help [here](https://github.com/protex/better-digraphs.nvim/blob/8aac75b17ba8ade660e4b66eef91e684909e723c/lua/better-digraphs/init.lua#L17). So, in theory, any daigraph that is supported by default will be there.
