### ISSUE TITLE
Insert mode doesn't work with nvim 0.7.0-dev

### ISSUE THREAD

**Issue by Sangdol** [protex/better-digraphs.nvim#2]
Hello,

Thanks for the awesome Plugin.

I just noticed that it doesn't insert a digraph properly when I use it in insert mode with nvim 0.7.0-dev.

When I tried to add a digraph, Better Digraphs behaves as if it tries to insert a combination of characters in normal mode.

This is the version of my nvim:

> NVIM v0.7.0-dev+1337-g72652cbc4
> Build type: Release
> LuaJIT 2.1.0-beta3
>
> Features: +acl +iconv +tui

I've updated it to the latest version but it could be due to an issue of nvim since it's still at the development build stage but I thought it'd be better to report it.

Thanks.

**Comment by protex** [comment]
Thanks for the heads up. I had actually noticed but haven't had a change to implement a fix yet.

**Comment by protex** [comment]
Fixed this issue for neovim 0.7. To get the fix please use the unstable branch.
