### ISSUE TITLE
Does not work when using non-standard mapping for digraphs

### ISSUE THREAD

**Issue by Mange** [protex/better-digraphs.nvim#8]
I've rebound <kbd>Ctrl</kbd>+<kbd>K</kbd> to show method signature (to mirror <kbd>Shift</kbd>+<kbd>K</kbd> in normal mode) and have placed digraphs on <kbd>Ctrl</kbd>+<kbd>L</kbd>.

Trying to use better-digraphs fails because it hardcodes feeding the `^K` control character.

**Comment by protex** [comment]
I'm actually not sure how to get around this. Can you show me the mapping you're using to place diagraphs on `Ctrl` + `L`, that may help me out.

**Comment by Mange** [comment]
https://github.com/Mange/dotfiles/blob/3478771b7308b146cdcb12802c9c6e3342ed8126/config/nvim/lua/mange/mappings.lua#L181-L182

I think this represents `inoremap <C-l> <C-k>` in Vimscript.

**Comment by protex** [comment]
Ah, I see. So, I just need to provide a way for the control character to be configured. I'll look into it. Thanks for the feedback.
